#!/bin/bash

# postinst
useradd brubeck

# Enable the daemon
systemctl daemon-reload
systemctl enable brubeck-biz
systemctl enable brubeck-tech

# Start the service
service brubeck-biz  start
service brubeck-tech start

