#!/bin/bash

# prerm

# Stop the service
service brubeck-biz  stop
service brubeck-tech stop

# Remove the daemon
rm -f /lib/systemd/system/brubeck-biz.service /lib/systemd/system/brubeck-tech.service
systemctl daemon-reload

# Remove group
userdel brubeck